name: Release Project

on:
   push:
      branches:
         - main
      paths:
         - CHANGELOG.md
   workflow_dispatch:

jobs:
   release:
      permissions:
         actions: write
         checks: write
         contents: write
         deployments: write
         id-token: write
         issues: write
         discussions: write
         packages: write
         pages: write
         pull-requests: write
         repository-projects: write
         security-events: write
         statuses: write
      uses: Azure/action-release-workflows/.github/workflows/release_js_project.yaml@e4a1a0385530d6861c9a9b7262058ad33b10c769
      with:
         changelogPath: ./CHANGELOG.md
